/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRecordRouteImport } from './routes/track-record'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharityRouteImport } from './routes/charity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsSlugRouteImport } from './routes/artists.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const TrackRecordRoute = TrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharityRoute = CharityRouteImport.update({
  id: '/charity',
  path: '/charity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const ArtistsSlugRoute = ArtistsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArtistsRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/charity': typeof CharityRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-record': typeof TrackRecordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artists/': typeof ArtistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/charity': typeof CharityRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-record': typeof TrackRecordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artists': typeof ArtistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/charity': typeof CharityRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-record': typeof TrackRecordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/artists/$slug': typeof ArtistsSlugRoute
  '/artists/': typeof ArtistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artists'
    | '/auth'
    | '/charity'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/track-record'
    | '/admin'
    | '/artists/$slug'
    | '/artists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/charity'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/track-record'
    | '/admin'
    | '/artists/$slug'
    | '/artists'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/artists'
    | '/auth'
    | '/charity'
    | '/contact'
    | '/shop'
    | '/sitemap.xml'
    | '/track-record'
    | '/_authenticated/admin'
    | '/artists/$slug'
    | '/artists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AuthRoute: typeof AuthRoute
  CharityRoute: typeof CharityRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRecordRoute: typeof TrackRecordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-record': {
      id: '/track-record'
      path: '/track-record'
      fullPath: '/track-record'
      preLoaderRoute: typeof TrackRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charity': {
      id: '/charity'
      path: '/charity'
      fullPath: '/charity'
      preLoaderRoute: typeof CharityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/artists/$slug': {
      id: '/artists/$slug'
      path: '/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof ArtistsSlugRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ArtistsRouteChildren {
  ArtistsSlugRoute: typeof ArtistsSlugRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsSlugRoute: ArtistsSlugRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  AuthRoute: AuthRoute,
  CharityRoute: CharityRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRecordRoute: TrackRecordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
